# Generated by Django 3.0.8 on 2020-07-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200719_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='platforms',
            field=models.CharField(choices=[('WHATSAPP', 'Text/WhatsApp/Call'), ('TEXT/CALL', 'Text/Call')], max_length=9, null=True),
        ),
    ]
