# Generated by Django 3.0.8 on 2020-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_phonenumber_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='platforms',
            field=models.CharField(choices=[('WHATSAPP', 'Text/WhatsApp/Call'), ('TEXT/CALL', 'Text/Call')], default='TEXT/CALL', max_length=9, null=True),
        ),
    ]
