# Generated by Django 3.0.8 on 2020-08-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200821_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_json_type', models.CharField(choices=[('Feature', 'Feature')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='GeometryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_type', models.CharField(choices=[('Point', 'Point'), ('MultiPoint', 'MultiPoint'), ('LineString', 'LineString'), ('MultiLineString', 'MultiLineString'), ('Polygon', 'Polygon'), ('MultiPolygon', 'MultiPolygon'), ('GeometryCollection', 'GeometryCollection')], max_length=18)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry_object', to='core.Feature')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('geometry_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.GeometryObject')),
            ],
        ),
    ]
