# Generated by Django 3.0.8 on 2020-08-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200825_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='geo_json_type',
            field=models.CharField(choices=[('Feature', 'Feature')], default='Feature', max_length=7),
        ),
        migrations.AlterField(
            model_name='geometryobject',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='core.Feature'),
        ),
    ]
