# Generated by Django 3.0.8 on 2020-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200825_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='alt_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feature',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
