# Generated by Django 3.0.8 on 2020-08-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200825_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='GeoJSONFeature',
        ),
    ]
