# Generated by Django 3.0.8 on 2020-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200825_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsonfeature',
            name='alt_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
