# Generated by Django 3.0.8 on 2020-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200825_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonfeature',
            name='associated',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
