# Generated by Django 3.0.8 on 2020-08-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_geojsonfeature_associated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geojsonfeature',
            old_name='associated',
            new_name='associated_with',
        ),
    ]
