# Generated by Django 3.0.8 on 2020-08-25 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200825_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='geometry_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='core.GeometryObject'),
        ),
    ]
