# Generated by Django 3.0.8 on 2020-08-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200825_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='marker',
            field=models.CharField(choices=[('START', 'start'), ('END', 'end'), ('NONE', 'none')], default='NONE', max_length=5),
        ),
    ]
