# Generated by Django 3.0.8 on 2020-08-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_position_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(default='', upload_to='assets/'),
        ),
    ]
