# Generated by Django 3.0.8 on 2020-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_position_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='criteria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='max_tenure',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='num_awards',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='special',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
