# Generated by Django 3.0.8 on 2020-09-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200901_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='method',
            new_name='method_of_selection',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='num_awards',
            new_name='number_of_awards',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='special',
            new_name='special_requirements',
        ),
    ]
