# Generated by Django 3.0.8 on 2020-09-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200901_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='description',
        ),
    ]
