# Generated by Django 3.0.8 on 2020-08-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200829_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
