# Generated by Django 3.0.8 on 2020-09-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_scholarship_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='details',
            new_name='additional_details',
        ),
    ]
