# Generated by Django 3.0.8 on 2020-09-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200901_2311'),
        ('core', '0030_auto_20200829_0758'),
    ]

    operations = [
    ]
