# Generated by Django 3.0.8 on 2020-07-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_phonenumber_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.PhoneNumber'),
        ),
    ]
