# Generated by Django 3.0.8 on 2020-07-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
