# Generated by Django 3.0.8 on 2020-07-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200718_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='position',
            new_name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('OFFICE', 'Office'), ('STAFF', 'Staff'), ('OTHER', 'Other')], default='OTHER', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(choices=[('CHEM', 'Chemistry'), ('COMP', 'Computing'), ('GEO', 'Geography and Geology'), ('LIFE', 'Life Sciences'), ('MATH', 'Mathematics'), ('PHYS', 'Physics'), ('OTHER', 'Other')], default='OTHER', max_length=5),
            preserve_default=False,
        ),
    ]
