# Generated by Django 3.0.8 on 2020-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200716_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date_time', models.CharField(max_length=50)),
                ('end_date_time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
