# Generated by Django 3.0.8 on 2020-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200718_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency'), ('OFFICE', 'Office'), ('FACULTY/STAFF', 'Faculty/Staff'), ('OTHER', 'Other')], max_length=13),
        ),
    ]
