# Generated by Django 3.0.8 on 2020-07-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200719_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
    ]
