# Generated by Django 3.0.8 on 2020-07-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200719_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='platforms',
            field=models.CharField(choices=[('TEXT/CALL', 'Text/Call'), ('WHATSAPP', 'Text/WhatsApp/Call')], default='TEXT/CALL', max_length=9, null=True),
        ),
    ]
